from Sample import onefileanalysis
teste = onefileanalysis.OMA('03-07-2019-stabilitystudies-5files.txt')
teste.rawdataplot18()
frequencyrange, yaxis, left, right = teste.FDD(desiredmaxfreq=10, numoflinestoplot=1, sensors=[9,10,11,15,16,17])
teste.spectrogram(channel=9)
peaks = teste.peakpicking()
MACmatrix = teste.MAC()
teste.MACplot(MACmatrix)
newmodalfreq, goodindexinfullrange, newMACmatrix = teste.MACselection(MACmatrix)
teste.MACplot(newMACmatrix)
teste.enhancedfdd()
